// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	consensus "source.quilibrium.com/quilibrium/monorepo/consensus"

	models "source.quilibrium.com/quilibrium/monorepo/consensus/models"
)

// VoteProcessorFactory is an autogenerated mock type for the VoteProcessorFactory type
type VoteProcessorFactory[StateT models.Unique, VoteT models.Unique] struct {
	mock.Mock
}

// Create provides a mock function with given fields: tracer, proposal
func (_m *VoteProcessorFactory[StateT, VoteT]) Create(tracer consensus.TraceLogger, proposal *models.SignedProposal[StateT, VoteT]) (consensus.VerifyingVoteProcessor[StateT, VoteT], error) {
	ret := _m.Called(tracer, proposal)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 consensus.VerifyingVoteProcessor[StateT, VoteT]
	var r1 error
	if rf, ok := ret.Get(0).(func(consensus.TraceLogger, *models.SignedProposal[StateT, VoteT]) (consensus.VerifyingVoteProcessor[StateT, VoteT], error)); ok {
		return rf(tracer, proposal)
	}
	if rf, ok := ret.Get(0).(func(consensus.TraceLogger, *models.SignedProposal[StateT, VoteT]) consensus.VerifyingVoteProcessor[StateT, VoteT]); ok {
		r0 = rf(tracer, proposal)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(consensus.VerifyingVoteProcessor[StateT, VoteT])
		}
	}

	if rf, ok := ret.Get(1).(func(consensus.TraceLogger, *models.SignedProposal[StateT, VoteT]) error); ok {
		r1 = rf(tracer, proposal)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewVoteProcessorFactory creates a new instance of VoteProcessorFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVoteProcessorFactory[StateT models.Unique, VoteT models.Unique](t interface {
	mock.TestingT
	Cleanup(func())
}) *VoteProcessorFactory[StateT, VoteT] {
	mock := &VoteProcessorFactory[StateT, VoteT]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
