{
 "title": "BlossomSub",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(blossomsub_add_peer_total,job)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(blossomsub_add_peer_total{job=\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Message delivery rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "avg by (bitmask) (rate(blossomsub_deliver_message_total{job=~\"$job\", instance=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Message validate rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "avg by (bitmask) (rate(blossomsub_validate_message_total{job=~\"$job\", instance=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Message reject rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "avg by (bitmask, reason) (rate(blossomsub_reject_message_total{job=~\"$job\", instance=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "{{bitmask}} - {{reason}}"
    }
   ]
  },
  {
   "title": "Message duplicate rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "avg by (bitmask) (rate(blossomsub_duplicate_message_total{job=~\"$job\", instance=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Gossip", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Sent IWANT message count histogram",
   "type": "timeseries",
   "description": "The number of message IDs provided in IWANT control messages sent to remote peers.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(blossomsub_iwant_messages_bucket{job=~\"$job\", instance=~\"$host\", direction=\"send\"}[$__rate_interval]))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, rate(blossomsub_iwant_messages_bucket{job=~\"$job\", instance=~\"$host\", direction=\"send\"}[$__rate_interval]))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.5, rate(blossomsub_iwant_messages_bucket{job=~\"$job\", instance=~\"$host\", direction=\"send\"}[$__rate_interval]))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Sent IHAVE message count histogram",
   "type": "timeseries",
   "description": "The number of message IDs in IHAVE control messages which have been successfully sent to a remote peer.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(bitmask, le) (rate(blossomsub_ihave_messages_bucket{job=~\"$job\", instance=~\"$host\", direction=\"send\"}[$__rate_interval])))",
     "legendFormat": "{{bitmask}} - P95"
    }
   ]
  },
  {
   "title": "Received IWANT message count histogram",
   "type": "timeseries",
   "description": "The number of message IDs provided in IWANT control messages received from remote peers.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(blossomsub_iwant_messages_bucket{job=~\"$job\", instance=~\"$host\", direction=\"recv\"}[$__rate_interval]))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, rate(blossomsub_iwant_messages_bucket{job=~\"$job\", instance=~\"$host\", direction=\"recv\"}[$__rate_interval]))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.5, rate(blossomsub_iwant_messages_bucket{job=~\"$job\", instance=~\"$host\", direction=\"recv\"}[$__rate_interval]))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Received IHAVE message count histogram",
   "type": "timeseries",
   "description": "The number of message IDs in IHAVE control messages which have received from a remote peer.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(bitmask, le) (rate(blossomsub_ihave_messages_bucket{job=~\"$job\", instance=~\"$host\", direction=\"recv\"}[$__rate_interval])))",
     "legendFormat": "{{bitmask}} - P95"
    }
   ]
  },
  {
   "title": "Dropped IWANT message count histogram",
   "type": "timeseries",
   "description": "The number of message IDs provided in IWANT control messages which have not been sent to a remote peer due to an error (usually a full queue).",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(blossomsub_iwant_messages_bucket{job=~\"$job\", instance=~\"$host\", direction=\"drop\"}[$__rate_interval]))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, rate(blossomsub_iwant_messages_bucket{job=~\"$job\", instance=~\"$host\", direction=\"drop\"}[$__rate_interval]))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.5, rate(blossomsub_iwant_messages_bucket{job=~\"$job\", instance=~\"$host\", direction=\"drop\"}[$__rate_interval]))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Dropped IHAVE message count histogram",
   "type": "timeseries",
   "description": "The number of message IDs in IHAVE control messages which have not been sent to a remote peer due to an error (usually a full queue).",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(bitmask, le) (rate(blossomsub_ihave_messages_bucket{job=~\"$job\", instance=~\"$host\", direction=\"drop\"}[$__rate_interval])))",
     "legendFormat": "{{bitmask}} - P95"
    }
   ]
  },
  { "title": "Meshes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Peer count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "avg by (bitmask) (blossomsub_graft_total{job=~\"$job\", instance=~\"$host\"} - blossomsub_prune_total{job=~\"$job\", instance=~\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Graft rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "avg by (bitmask) (rate(blossomsub_graft_total{job=~\"$job\", instance=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prune rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "avg by (bitmask) (rate(blossomsub_prune_total{job=~\"$job\", instance=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RPCs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "RPC rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(blossomsub_send_rpc_total{job=~\"$job\", instance=~\"$host\"}[$__rate_interval])",
     "legendFormat": "Sent"
    },
    {
     "expr": "rate(blossomsub_recv_rpc_total{job=~\"$job\", instance=~\"$host\"}[$__rate_interval])",
     "legendFormat": "Received"
    },
    {
     "expr": "rate(blossomsub_drop_rpc_total{job=~\"$job\", instance=~\"$host\"}[$__rate_interval])",
     "legendFormat": "Dropped"
    }
   ]
  }
 ]
}