name: docker-build-test

on:
  push:
    branches: [rs-docker-optim]

concurrency:
  group: docker-build-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build (${{ matrix.task }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task:
          - build_node_amd64_linux
          - build_node_amd64_avx512_linux
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Pull LFS files
        run: git lfs pull

      - uses: docker/setup-buildx-action@v3

      - uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: task ${{ matrix.task }}
        run: task ${{ matrix.task }}
